config/routes.rb
Rails.application.routes.draw do

    root 'categories#index'

  resources :categories do
    resources :subcategories
  end

  resources :listings do
    resources :comments 
    collection do
     get 'search'
    end
    
  end

  devise_for :users 

  match '/help',    to: 'pages#help',     via: :get
  match '/scams',   to: 'pages#scams',    via: :get
  match '/contact', to: 'pages#contact',  via: :get
  match '/safety',  to: 'pages#safety',   via: :get
  match '/terms',   to: 'pages#terms',    via: :get
  match '/privacy', to: 'pages#privacy',  via: :get
  match '/about',   to: 'pages#about',    via: :get
  match '/mylistings',   to: 'listings#mylistings',    via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories
  has_many :listings             #sir added
  #def category #i added optional
		#params.require(:category).permit(:name)
	#end




end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :listing
  belongs_to :user
   validates :message, :title, presence: true, length: { minimum: 5, maximimum: 1000 }
   
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :category, required: false#, foreign_key: 'category_id' #sir added but false i add
  belongs_to :subcategory, required: false#, foreign_key: 'subcategory_id'
  belongs_to :user, required: false
  #validates :user_id, presence: true # just in case for more user security for each post it has userid
  validates_presence_of :title # we dont want empty title
  validates_presence_of :description # we dont want empty title
  validates_presence_of :city #we dont want empty city
  validates_presence_of :state #we dont want empty state

  has_many :comments, dependent: :destroy




  geocoded_by :full_address
  after_validation :geocode

  def full_address
    [city, state, zipcode].join(', ')
  end
  def self.search(params)
listings = Listing.where(category_id: params[:category].to_i) #.to_i nagareni chaldorecha
listings = listings.where("title LIKE ? OR description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%")if params[:search].present?
#listings =listings.where("title LIKE? or description LIKE?", params[:search], params[:search]) if params[:search].present?
listings = listings.near(params[:location], 20) if params[:location].present?
listings
end
end
  #def self.search(params) # making own search function
    #listings= Listing.where(category_id: params[:category].to_i) #defining a variable "listings"to grab whatever is in rhs
#works for postgresql
  #  listings =listings.where("title LIKE? or description LIKE?", params[:search], params[:search]) if params[:search].present?
#for sqlite you have to pass param as string

    #listings =listings.where("title LIKE? OR description LIKE?", "%#{params[:search]}%", "%#{params[:search]}%")if params[:search].present?
  #  listings = listings.near(params[:location], 20) if params[:location].present?
    #listings #finally returning the jumbo listings value
 #end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category, required: false
  #has_many :listings #added by me not sir

  #def subcategory # i added optional
		#params.require(:subcategory).permit(:name, :category_id)
	#end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :listings, dependent: :destroy # if user is deleted his all posts destroyed
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @societal = @categories[0] #id 1 bhayekoharu
    @onsale = @categories[1]
    @housing = @categories[2]
    @works = @categories[3]
    @services = @categories[4]
    @personal = @categories[5]
  end

  def show
    @listings =  Listing.where(category_id: params[:id])
    @category = Category.find(params[:id])  # FindMe > societal> clubs => helps to print societal

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	  def create
	  	 
		@listing = Listing.find(params[:listing_id])
		@comment = @listing.comments.create(comment_params.merge(user_id: current_user.id))  
	 	#@comment = @listing.comments.create(params[:comment].permit(:title, :message, :listing_id, :user_id))
		redirect_to listing_path(@listing) #redirect same pg itself
	end

	def destroy # deleting via user existence

		@comment = current_user.comments.find(params[:id])
		@comment.destroy

		redirect_back(fallback_location: root_path)
	end








	private
	def comment_params
      params.require(:comment).permit(:title, :message)
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
before_action :authenticate_user!,only: [:new, :create] # we dont want user to create listing when they are not logged in.we want users to create new account in order for them to create listing
#authenticate_user! is devise method
before_action :is_user?, only:[:edit, :update, :destroy] #edit and delete tags are not shown but if we click listings/8/edit , it will be redirected so we need to stop this

  def new
    @listing = Listing.new
  end


  def create # we have to hold paramaters.
    @listing = Listing.new(listing_params)
    @listing.user = current_user #current user is devise gem, just finding our current user id and putting into a listing user
    #if i not do above @listing.user = current_user then my user_id always nil in DB.
    if @listing.save
      redirect_to @listing
    else
  # redisplay the form if validation failed
    flash[:notice] = @listing.errors.full_messages.to_sentence
    render action: 'new'
    end
  end


  def show
    @listing = Listing.find(params[:id])
  end


  def search
  @listings = Listing.search(params)
  end

  def mylistings
    @listings = Listing.where(user: current_user)
  end

  def edit
    @listing = Listing.where(user: current_user)
    @listing = Listing.find(params[:id])
  end
  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)
    redirect_to @listing
  end

  def destroy
    @listing = Listing.where(user: current_user)
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to root_path
  end


  def is_user?
    @listing = Listing.find(params[:id])
    unless current_user = @listing.user
      redirect_to root_path, alert: "Sorry, you are not the user of this listing."
    end
  end


  private
  def listing_params
    params.require(:listing).permit(:title, :description, :city, :state, :zipcode,:category_id, :subcategory_id,) #table name and strong parameters. those parameters that are only used not all
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
  end
  def scams
  end
  def contact
  end
  def safety
  end
  def terms
  end
  def privacy
  end
  def about
  end


end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def show
      @listings =  Listing.where(:subcategory_id=> params[:id])
      #@category = Category.find(params[:id]) # yo garda category id ma 1 to 20 ko range bascha coz id will read subcategory params
      @category = Category.find(params[:category_id]) # output findme>societal
      @subcategory = Subcategory.find(params[:id])  #output findme>societal>games
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/categories/index.html.erb
<style>
 body {
    background-color: grey;
 }
</style>
  <div class="center-column">
    <div class="center-one">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'societal', category_path(@categories[0]) %></th>
        </tr>
        <tr>
          <td>
            <% @societal.subcategories.each do |subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name, category_subcategory_path(@societal, subcategory)%> </li>
              <%#<li>test</li> %>
              <%#<li>test</li> %>
              <%#<li>test</li> %>
            <%#<li>test</li> %>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'housing', category_path(@housing) %> </th>
        </tr>
        <tr>
          <td>
            <% @housing.subcategories.each do|subcategory| %>
            <ul>
              <li><%= link_to subcategory.name, category_subcategory_path(@housing, @housing.subcategories)%></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'services', category_path(@services) %></th>
        </tr>
        <tr>
          <td>
            <% @services.subcategories.each do|subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name, category_subcategory_path(@services, subcategory) %> </li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="center-two">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'onsale' , category_path(@onsale)%></th>
        </tr>
        <tr>
          <td>
            <% @onsale.subcategories.each do|subcategory| %>
            <ul>
              <li><%= link_to subcategory.name, category_subcategory_path(@onsale, subcategory)%></li>
            </ul>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <th class="table-header"><%= link_to 'works' , category_path(@works)%></th>
        </tr>
        <tr>
          <td>
            <% @works.subcategories.each do|subcategory| %>
            <ul class="left-list">
              <li><%= link_to subcategory.name, category_subcategory_path(@works, subcategory)%></li>
            </ul>
            <%end%>
          </td>
        </tr>
      </table>
    </div>
    <div class="center-three">
      <table>
        <tr>
          <th class="table-header"><%= link_to 'personal', category_path(@personal) %></th>
        </tr>
        <tr>
          <td>
            <% @personal.subcategories.each do |subcategory|%>
            <ul>
              <li><%= link_to subcategory.name, category_subcategory_path(@personal , subcategory) %></li>

            </ul>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

app/views/categories/new.html.erb
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > New listing 
    </div>
  </div>
</div>
<%#<div class="container"> %>
  <%#<div id="contact-area"> %>
    <%= form_for @listing do |f| %>
       <p><%= f.label :title %>
      <%= f.text_field :title %></p>
      <p><%= f.label :description %>
      <%= f.text_area :description %></p>
      <p>  <%= f.label :category_id %>
      <%= f.select :category_id, Category.all.map {|f| [f.name,f.id]} %> </p>
      <p>  <%= f.label :subcategory_id %>
      <%= f.select :subcategory_id, Subcategory.all.map {|f| [f.name,f.id]} %> </p>
      <p><%= f.label :city %>
      <%= f.text_field :city %></p>
      <p><%= f.label :state %>
      <%= f.text_field :state %></p>
      <p><%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: "zip-width", maxlength: "5" %></p><%# width and max length are optionalzip width makes box appear smaller and length 5 limits digits to 5. %>
      <p><%= f.submit class:"create-button" %> </p><%# class optional to make button prettier, mentioned in css %>
    <% end %>
  <%#</div>
</div> %>

app/views/categories/show.html.erb
<style>
body {
    background-color: grey;
}
</style>
<div class="center-column" >
  <div class="topbar">
    <div class="container">
      <div class="vertical-center">
        <%=link_to "FindMe",root_path  %>> <%= link_to @category.name, @category %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
       <div class="newest">Newest</div>
       <div class="oldest">Oldest</div>
       <div class="highest-price">Highest-price</div>
       <div class="lowest-price">Lowest-price</div>
     </div>
    <ul class="list-margin">

      <% if @listings.each do|listing| %>
      <li>
        <span>
          <%= listing.created_at.strftime('Printed on %B/%d/%Y')%> <%#time_ago_in_words(listing.created_at) %>
        </span>
        <%= link_to listing.title, listing %>(<%= listing.city %>, <%= listing.state %>)
      </li>
      <% end.empty?%>
       <p> Sorry, there are no posts in this category</p>
      <% end %>
    </ul>
  </div>
</div>

app/views/comments/_comment.html.erb
 


<u><%= comment.title %> </u> <br>
<%= comment.message %> <br>

<!-- <em>Posted by ID no.: </em>  <%=comment.user_id%> -->


<%# User.find(comment.user_id).email %> 
<%#@listing.comments.find(params[:id]).user %>
 

<%#@listing.comments.all.collect(&:user) %>


<% if current_user == comment.user %>
	<p> <%= link_to 'Delete', [comment.listing, comment], method: :delete, data: {confirm:"Are you sure you want to delete this comment?"} %></p> <br> 

<%end%>

 



 

app/views/comments/_form.html.erb
<%# unless current_user.is_a? GuestUser %>
<% if @listing.user = current_user %>
<%= form_for([@listing, @listing.comments.build]) do |f| %>
<p> <%= f.label :title %> </p>
<p> <%= f.text_field :title %> </p>
<p> <%= f.label :message %> </p>
<p> <%= f.text_area :message %> </p>
<%= f.submit %>
<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<%
=begin %>

<div class="rightbar">
    <ul class="rightbar-top">
      <%#<li>help and faq</li> %>
      <li> <%= link_to 'help and faq',help_path %></li>
      <%#<li>avoid scams & fraud</li> %>
      <li> <%= link_to 'avoid scams & fraud', scams_path %> </li>
      <li><%= link_to 'personal safety tips', safety_path %></li>
      <li class="rightbar-top"><%= link_to'terms of use', terms_path %></li>
      <li><%= link_to'privacy policy', privacy_path %></li>
      <li><%= link_to'about FindMe', about_path %></li>
      <li><%= link_to 'contact us', contact_path %></li>
    </ul>
  </div>



  <%
  =end %>

app/views/layouts/_header.html.erb
<%
=begin %>


  <div class="leftbar">
<%#    <a href="#"><h1>FindMe</h1></a> %>
    <%= link_to 'FindMe', category_path %>
    <ul>
      <%#<a href="#">post to classifieds</a> %>
      <%= link_to 'post to classifieds', new_listing_path %>
      <li>my account</li>
    </ul>
    <form>
      <p>search FindMe</p>
      <input type="text" name="firstname" placeholder="search" size="20">
      <br>
      <input type="text" name="firstname" placeholder="where" size="20">
      <br>
      <select>
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option value="mercedes">Mercedes</option>
        <option value="audi">Audi</option>
      </select>
      <button type="button">>
      </button>
    </form>
  </div>


<%
=end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FindMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render "layouts/partials/header" %>
    <%= render "layouts/partials/footer" %>
      <%#<%= slide_down_alerts %> <%#using gems slide down alerts but not working %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %>
       <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<div class="rightbar">
    <ul class="rightbar-top">
      <%#<li>help and faq</li> %>
      <li> <%= link_to 'help and faq',help_path %></li>
      <%#<li>avoid scams & fraud</li> %>
      <li> <%= link_to 'avoid scams & fraud', scams_path %> </li>
      <li><%= link_to 'personal safety tips', safety_path %></li>
      <li class="rightbar-top"><%= link_to'terms of use', terms_path %></li>
      <li><%= link_to'privacy policy', privacy_path %></li>
      <li><%= link_to'about', about_path %></li>
      <li><%= link_to 'contact us', contact_path %></li>
    </ul>
  </div>

app/views/layouts/partials/_header.html.erb
  <div class="leftbar">
  <%#  <a href="#"><h1>FindMe</h1></a> %>
  <h1>  <%= link_to 'FindMe', categories_path %></h1>
    <ul>
      <%#<a href="#">post to classifieds</a> %>
    <li>  <%= link_to 'post to classifieds', new_listing_path %></li>
      <% if user_signed_in? %>
          <li><%= link_to 'My Accout', edit_user_registration_path %></li>
            <li><%= link_to 'My Listings', mylistings_path %></li>
          <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>

    <%= form_tag search_listings_path, method: :get do |f| %>
        <p>Search </p>
        <%= text_field_tag :search, nil, placeholder: 'search' %>
        <%= text_field_tag :location, nil, placeholder: 'nearby' %>
        <%= select_tag :category, options_for_select(Category.all.map{|c|[c.name, c.id]}) %>
        
        <%= submit_tag 'Go' %>


<% end %>


  </div>

app/views/listings/edit.html.erb
<style>
body {
    background-color: grey;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > works > construction
    </div>
  </div>
</div>
<%#<div class="container"> %>
  <%#<div id="contact-area"> %>
    <%= form_for @listing do |f| %>
       <p><%= f.label :title %>
      <%= f.text_field :title %></p>
      <p><%= f.label :description %>
      <%= f.text_area :description %></p>
      <p>  <%= f.label :category_id %>
      <%= f.select :category_id, Category.all.map {|f| [f.name,f.id]} %> </p>
      <p>  <%= f.label :subcategory_id %>
      <%= f.select :subcategory_id, Subcategory.all.map {|f| [f.name,f.id]} %> </p>
      <p><%= f.label :city %>
      <%= f.text_field :city %></p>
      <p><%= f.label :state %>
      <%= f.text_field :state %></p>
      <p><%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: "zip-width", maxlength: "5" %></p><%# width and max length are optionalzip width makes box appear smaller and length 5 limits digits to 5. %>
      <p><%= f.submit class:"create-button" %> </p><%# class optional to make button prettier, mentioned in css %>
    <% end %>
  <%#</div>
</div> %>

app/views/listings/mylistings.html.erb
<style>
body {
    background-color: grey;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > my listing
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
     <div class="newest">newest</div>
     <div class="oldest">oldest</div>
     <div class="highest-price">highest-price</div>
     <div class="lowest-price">lowest-price</div>
   </div>
  <ul class="list-margin">
    <% if @listings.each do|listing| %>
    <li>
      <span>
        <%= listing.created_at.strftime('Printed on %B/%d/%Y')%> <%#time_ago_in_words(listing.created_at) %>
      </span>
      <%= link_to listing.title, listing %>(<%= listing.city %>, <%= listing.state %>)
    </li>
    <% end.empty?%>
     <p> Sorry, there are no posts in this category :(</p>
    <% end %>

  </ul>
</div>

app/views/listings/new.html.erb
<style>
body {
    background-color: grey;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > New listing
    </div>
  </div>
</div>
<%#<div class="container"> %>
  <%#<div id="contact-area"> %>
    <%= form_for @listing do |f| %>
       <p><%= f.label :title %>
      <%= f.text_field :title %></p>
      <p><%= f.label :description %>
      <%= f.text_area :description %></p>
      <p>  <%= f.label :category_id %>
      <%= f.select :category_id, Category.all.map {|f| [f.name,f.id]} %> </p>
      <p>  <%= f.label :subcategory_id %>
      <%= f.select :subcategory_id, Subcategory.all.map {|f| [f.name,f.id]} %> </p>
      <p><%= f.label :city %>
      <%= f.text_field :city %></p>
      <p><%= f.label :state %>
      <%= f.text_field :state %></p>
      <p><%= f.label :zipcode %>
      <%= f.text_field :zipcode, class: "zip-width", maxlength: "5" %></p><%# width and max length are optionalzip width makes box appear smaller and length 5 limits digits to 5. %>
      <p><%= f.submit class:"create-button" %> </p><%# class optional to make button prettier, mentioned in css %>
    <% end %>
  <%#</div>
</div> %>

app/views/listings/search.html.erb
<style>
body {
    background-color: grey;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>> Search
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
     <div class="newest">Newest</div>
     <div class="oldest">Oldest</div>
     <div class="highest-price">Highest-price</div>
     <div class="lowest-price">Lowest-price</div>
   </div>
  <ul class="list-margin">

    <% if @listings.each do|listing| %>
    <li>
      <span>
        <%= listing.created_at.strftime('Printed on %B/%d/%Y')%> <%#time_ago_in_words(listing.created_at) %>
      </span>
      <%= link_to listing.title, listing %>(<%= listing.city %>, <%= listing.state %>)
    </li>
    <% end.empty?%>
     <p> Sorry, there are no posts in this category :(</p>
    <% end %>
  </ul>
</div>

app/views/listings/show.html.erb
<style>
body {
    background-color: grey;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %> > <%=@listing.title %>
    </div>
  </div>
</div>
<div class="container">
  <div>
    <!-- <button type="button">reply</button> -->
    <style>
body {
    background-color: grey;
}
</style>
    posted <%= time_ago_in_words(@listing.created_at) %>
    <h1 class="listing-header"><%= @listing.title %></h1>
    
      <% if @listing.user = current_user %>
      <div class="box">
          <p><%= link_to 'Edit', edit_listing_path %></p>
      <%#<%= link_to 'Delete', delete_listing_path :::::
      cannot do this becaude delete has no path so we want to show which post u wanna delete and say methd also because delete always needs method %>
          <p><%= link_to 'Delete', @listing, data: {confirm:"Are you sure you want to delete this listing?"}, method: :delete %></p>
        <%else%>
        <%end %>
    </div>
    <p> <%= @listing.description %></p>
    
  </div>
  <footer>
    <p>post id: <%= @listing.id%></p> <%# list is post %>
   <%# posted <%=@listing.created_at%>
   <p>posted at: <%= time_ago_in_words(@listing.created_at) %> ago</p>



  



  </footer>
</div>

<br>
<% if @listing.user = current_user %>
  <strong>Add a comment</strong>
<% end %>
<%= render 'comments/form' %> <br>
<h3><%= @listing.comments.count %> comments </h3> <br>
<%= render @listing.comments %> 

app/views/pages/about.html.erb
<style>
body {
    background-color: green;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > about
    </div>
  </div>
</div>
<div class="container">
    <p> This is the About page. If you need more informations contact the web developer team
    </p>
</div>

app/views/pages/contact.html.erb
<style>
body {
    background-color: green;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > contact
    </div>
  </div>
</div>
<div class="container">
    <p> This is the Contact page. If you need more informations contact the web developer team
    </p>
</div>

app/views/pages/help.html.erb
<style>
body {
    background-color: green;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > help
    </div>
  </div>
</div>
<div class="container">
    <p> This is the help page. If you need more informations contact the web developer team
    </p>
</div>

app/views/pages/privacy.html.erb
<style>
body {
    background-color: green;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > privacy
    </div>
  </div>
</div>
<div class="container">
    <p> This is the privacy page. If you need more informations contact the web developer team
    </p>
</div>

app/views/pages/safety.html.erb
<style>
body {
    background-color: green;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > safety
    </div>
  </div>
</div>
<div class="container">
    <p> This is the Safety page. If you need more informations contact the web developer team
    </p>
</div>

app/views/pages/scams.html.erb
<style>
body {
    background-color: green;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > scams
    </div>
  </div>
</div>
<div class="container">
    <p> This is the Scams and fraud page. If you need more informations contact the web developer team
    </p>
</div>

app/views/pages/terms.html.erb
<style>
body {
    background-color: green;
}
</style>
<div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%=link_to "FindMe",root_path  %>  > terms
    </div>
  </div>
</div>
<div class="container">
    <p> This is the Terms and condition page. If you need more informations contact the web developer team
    </p>
</div>

app/views/subcategories/show.html.erb
<style>
body {
    background-color: green;
}
</style>
 <div class="topbar">
  <div class="container">
    <div class="vertical-center">
      <%= link_to "FindMe", root_path %>> <%=link_to @category.name, @category %> > <%= @subcategory.name%>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
     <div class="newest">newest</div>
     <div class="oldest">oldest</div>
     <div class="highest-price">highest-price</div>
     <div class="lowest-price">lowest-price</div>
   </div>
  <ul class="list-margin">
    <% if @listings.each do|listing| %>
    <li>
      <span>
        <%= listing.created_at.strftime('Printed on %B/%d/%Y')%> <%#time_ago_in_words(listing.created_at) %>
      </span>
      <%= link_to listing.title, listing %>(<%= listing.city %>, <%= listing.state %>)
    </li>
    <% end.empty?%>
     <p> Sorry, there are no posts in this category</p>
    <% end %>
  </ul>
</div>